module.exports = {
  "core/wcm/components/accordion/v1/accordion": require("./accordion"),
  "core/wcm/components/breadcrumb/v2/breadcrumb": require("./breadcrumb"),
  "core/wcm/components/button/v1/button": require("./button"),
  "core/wcm/components/carousel/v1/carousel": require("./carousel"),
  "core/wcm/components/container/v1/container": require("./container"),
  "core/wcm/components/contentfragment/v1/contentfragment": require("./contentfragment"),
  "core/wcm/components/contentfragmentlist/v1/contentfragmentlist": require("./contentfragmentlist"),
  "core/wcm/components/download/v1/download": require("./download"),
  "core/wcm/components/embed/v1/embed": require("./embed"),
  "core/wcm/components/experiencefragment/v1/experiencefragment": require("./experiencefragment"),
  "core/wcm/components/form/container/v2/container": require("./form-container"),
  "core/wcm/components/form/button/v2/button": require("./form-button"),
  "core/wcm/components/form/options/v2/options": require("./form-options"),
  "core/wcm/components/form/text/v2/text": require("./form-text"),
  "core/wcm/components/image/v2/image": require("./image"),
  "core/wcm/components/languagenavigation/v1/languagenavigation": require("./languagenavigation"),
  "core/wcm/components/list/v2/list": require("./list"),
  "core/wcm/components/navigation/v1/navigation": require("./navigation"),
  "core/wcm/components/pdfviewer/v1/pdfviewer": require("./pdfviewer"),
  "core/wcm/components/progressbar/v1/progressbar": require("./progressbar"),
  "core/wcm/components/search/v1/search": require("./search"),
  "core/wcm/components/separator/v1/separator": require("./separator"),
  "core/wcm/components/tabs/v1/tabs": require("./tabs"),
  "core/wcm/components/teaser/v1/teaser": require("./teaser"),
  "core/wcm/components/text/v2/text": require("./text"),
  "core/wcm/components/title/v2/title": require("./title"),
};
