module.exports = {
  accordion: require("./accordion"),
  breadcrumb: require("./breadcrumb"),
  button: require("./button"),
  carousel: require("./carousel"),
  container: {
    default: require("./container"),
    root: require("./container/root"),
  },
  contentfragment: require("./contentfragment"),
  contentfragmentlist: require("./contentfragmentlist"),
  download: require("./download"),
  embed: require("./embed"),
  experiencefragment: {
    default: require("./experiencefragment"),
    siteElements: require("./experiencefragment/site-elements"),
  },
  form: {
    container: require("./form-container"),
    button: require("./form-button"),
    options: require("./form-options"),
    text: require("./form-text"),
  },
  image: require("./image"),
  languagenavigation: require("./languagenavigation"),
  list: require("./list"),
  navigation: require("./navigation"),
  page: require("./page"),
  pdfviewer: require("./pdfviewer"),
  progressbar: require("./progressbar"),
  search: require("./search"),
  separator: require("./separator"),
  tabs: require("./tabs"),
  teaser: require("./teaser"),
  text: require("./text"),
  title: require("./title"),
};
